const dataSet = [
  {
    // "title": "Sky Mansion",
    id: 0,
    about:
      "Nestled in the heart of Bengaluru, Karnataka, India, the Sky Mansion is a luxurious residential paradise. Owned by Harish Kushwaha, this stunning property offers a glimpse of modern elegance and comfort.This spacious apartment is spread over 600 square feet, with 2 beautifully appointed rooms, each featuring attached bathrooms for your convenience. The kitchen is fully equipped and ready to cater to your culinary desires.",
    landType: "Residential",
    owner: {
      name: "Harish Kushwaha",
      mobile: "+911234567890",
      email: "harish@gmail.com",
      governmentID: 11223344556,
    },
    price: 3200,
    currency: "INR",
    image: [
      "https://i.postimg.cc/jdkKmrDv/image.png",
      "https://i.postimg.cc/jdkKmrDv/image.png",
      "https://i.postimg.cc/jdkKmrDv/image.png",
    ],
    coordinates: {
      latitude: 12.9716,
      longitude: 77.5946,
    },
    address: "Sree Raghavendra complex, 3rd Cross Road",
    pincode: 560003,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "Parking Allotment", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Flat",
      channel: [
        { ownerNum: 1, ownerName: "Rajveer" },
        { ownerNum: 2, ownerName: "Satyam" },
        { ownerNum: 3, ownerName: "Harish Kushwaha" },
      ],
      loanAmount: 0,
      isFlat: "Yes",
      propertyData: {
        complaincesFollowed: "Yes",
        parkingAlloted: "No",
        towerNumber: "1C",
        flatNumber: 324,
        size: 600,
        noOfRooms: 2,
        bathroomAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "Yes",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
  {
    // "title": "Rainbow Apartments",
    id: 1,
    about:
      "Nestled in the vibrant city of Panvel, Maharashtra, India, Rainbow Apartments is a magnificent residential haven. Owned by the esteemed Sanjeev Kumar, this splendid property offers an exquisite living experience. This spacious apartment covers an expansive area of 750 square feet and boasts 4 elegantly designed rooms, each equipped with attached bathrooms for your convenience. The well-furnished kitchen is ready to cater to your culinary delights.",
    landType: "Residential",
    owner: {
      name: "Sanjeev Kumar",
      mobile: "+914574123658",
      email: "sanjeev@gmail.com",
      governmentID: 998877445566,
    },
    price: 8765,
    currency: "INR",
    image: [
      "https://i.postimg.cc/FRQhpgY4/image.png",
      "https://i.postimg.cc/FRQhpgY4/image.png",
      "https://i.postimg.cc/FRQhpgY4/image.png",
    ],
    coordinates: {
      latitude: 19.030914,
      longitude: 73.060073,
    },
    address: "Sector 2, Kharghar Station Road",
    pincode: 410210,
    city: "Panvel",
    state: "Maharashtra",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "Parking Allotment", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Flat",
      channel: [{ ownerNum: 1, ownerName: "Sanjeev Kumar" }],
      loanAmount: 0,
      isFlat: "Yes",
      propertyData: {
        complaincesFollowed: "Yes",
        parkingAlloted: "No",
        towerNumber: "9A",
        flatNumber: 634,
        size: 750,
        noOfRooms: 4,
        bathroomAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "Yes",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
  {
    // "title": "Vijay Bungalow",
    id: 2,
    about:
      "Nestled on the picturesque coastline of a secluded bay, Sunset Haven stands as an architectural masterpiece of unparalleled beauty and luxury. This sprawling bungalow offers an idyllic retreat for those seeking the ultimate in privacy and tranquility. With its commanding views of the pristine beach, the bungalow is a sanctuary where natural beauty meets modern elegance.",
    landType: "Residential",
    owner: {
      name: "Ranu Kumar",
      mobile: "+914985462157",
      email: "runu@gmail.com",
      governmentID: 4455887769911,
    },
    price: 9283,
    currency: "INR",
    image: [
      "https://i.postimg.cc/mZHQtbs1/image.png",
      "https://i.postimg.cc/mZHQtbs1/image.png",
      "https://i.postimg.cc/mZHQtbs1/image.png",
    ],
    coordinates: {
      latitude: 19.15607,
      longitude: 75.267176,
    },
    address: "Rainbow Street, Panvel",
    pincode: 432210,
    city: "Panvel",
    state: "Maharashtra",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Bungalow",
      channel: [{ ownerNum: 1, ownerName: "Ranu Kumar" }],
      loanAmount: 0,
      isFlat: "No",
      propertyData: {
        complianceFollowed: "Yes",
        parkingAllotted: "Yes",
        plotNumber: "12B",
        size: 1500,
        noOfRooms: 5,
        bathroomsAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "No",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
  {
    title: "Ocean View Villa",
    id: 1,
    about:
      "Located on the serene coastline of Goa, India, the Ocean View Villa offers breathtaking views of the sea. This luxurious villa features spacious living areas, state-of-the-art amenities, and private beach access. With 5 bedrooms, each with its own en-suite bathroom, this villa provides the perfect blend of comfort and extravagance.",
    landType: "Residential",
    owner: {
      name: "Priya Sharma",
      mobile: "+919876543210",
      email: "priya@gmail.com",
      governmentID: 99887766554,
    },
    price: 7500,
    currency: "INR",
    image: [
      "https://i.postimg.cc/fRN46Twc/image.png",
      "https://i.postimg.cc/fRN46Twc/image.png",
      "https://i.postimg.cc/fRN46Twc/image.png",
    ],
    coordinates: {
      latitude: 15.2993,
      longitude: 74.124,
    },
    address: "Ocean View Villa, Beach Road",
    pincode: 403002,
    city: "Goa",
    state: "Goa",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "Parking Allotment", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Villa",
      channel: [
        { ownerNum: 1, ownerName: "Rahul Sharma" },
        { ownerNum: 2, ownerName: "Priya Sharma" },
      ],
      loanAmount: 0,
      isFlat: "No",
      propertyData: {
        complaincesFollowed: "Yes",
        parkingAlloted: "Yes",
        towerNumber: null,
        flatNumber: null,
        size: null,
        noOfRooms: 5,
        bathroomAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "Yes",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
  {
    title: "Hillside Retreat",
    id: 2,
    about:
      "Escape to the tranquility of the mountains with Hillside Retreat. Situated amidst lush greenery in Himachal Pradesh, India, this charming cottage offers a cozy retreat from the hustle and bustle of city life. With 3 bedrooms, a spacious living area, and a fully equipped kitchen, this retreat is perfect for nature lovers and adventure seekers alike.",
    landType: "Residential",
    owner: {
      name: "Amit Patel",
      mobile: "+919876543210",
      email: "amit@gmail.com",
      governmentID: 11223344556,
    },
    price: 5000,
    currency: "INR",
    image: [
      "https://i.postimg.cc/s2LTCwpk/image.png",
      "https://i.postimg.cc/s2LTCwpk/image.png",
      "https://i.postimg.cc/s2LTCwpk/image.png",
    ],
    coordinates: {
      latitude: 31.1048,
      longitude: 77.1734,
    },
    address: "Hillside Retreat, Mountain View Road",
    pincode: 175131,
    city: "Shimla",
    state: "Himachal Pradesh",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "Parking Allotment", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Cottage",
      channel: [{ ownerNum: 1, ownerName: "Amit Patel" }],
      loanAmount: 0,
      isFlat: "No",
      propertyData: {
        complaincesFollowed: "Yes",
        parkingAlloted: "No",
        towerNumber: null,
        flatNumber: null,
        size: null,
        noOfRooms: 3,
        bathroomAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "Yes",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
  {
    title: "City Heights Apartment",
    id: 3,
    about:
      "Experience urban living at its finest with City Heights Apartment. Located in the bustling city of Mumbai, Maharashtra, India, this contemporary apartment offers convenient access to shopping, dining, and entertainment. With 3 bedrooms, a modern kitchen, and a spacious living area, this apartment is perfect for young professionals and families alike.",
    landType: "Residential",
    owner: {
      name: "Amit Shah",
      mobile: "+919876543210",
      email: "amit@gmail.com",
      governmentID: 99887766554,
    },
    price: 6000,
    currency: "INR",
    image: [
      "https://i.postimg.cc/8cQwjcXw/image.png",
      "https://i.postimg.cc/8cQwjcXw/image.png",
      "https://i.postimg.cc/8cQwjcXw/image.png",
    ],
    coordinates: {
      latitude: 19.076,
      longitude: 72.8777,
    },
    address: "City Heights Apartment, Main Street",
    pincode: 400001,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "Parking Allotment", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Apartment",
      channel: [{ ownerNum: 1, ownerName: "Amit Shah" }],
      loanAmount: 0,
      isFlat: "Yes",
      propertyData: {
        complaincesFollowed: "Yes",
        parkingAlloted: "Yes",
        towerNumber: "B2",
        flatNumber: 1203,
        size: 1200,
        noOfRooms: 3,
        bathroomAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "Yes",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
  {
    title: "Lakefront Bungalow",
    id: 4,
    about:
      "Indulge in luxury living at Lakefront Bungalow. Situated on the banks of Powai Lake in Mumbai, Maharashtra, India, this magnificent bungalow offers stunning views and unparalleled tranquility. With 7 bedrooms, a private swimming pool, and lush green gardens, this bungalow is an oasis of comfort and style.",
    landType: "Residential",
    owner: {
      name: "Rahul Singh",
      mobile: "+919876543210",
      email: "rahul@gmail.com",
      governmentID: 11223344556,
    },
    price: 12000,
    currency: "INR",
    image: [
      "https://i.postimg.cc/52738nkX/image.png",
      "https://i.postimg.cc/52738nkX/image.png",
      "https://i.postimg.cc/52738nkX/image.png",
    ],
    coordinates: {
      latitude: 19.1197,
      longitude: 72.9073,
    },
    address: "Lakefront Bungalow, Lakeside Drive",
    pincode: 400076,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    documents: [
      { name: "Deed", status: "Approved" },
      { name: "Channel Document", status: "Approved" },
      { name: "Encurbrance Certificate", status: "Approved" },
      { name: "Occupancy Certificate", status: "Approved" },
      { name: "Allotment", status: "Approved" },
      { name: "Tax Reciept", status: "Approved" },
      { name: "Parking Allotment", status: "Approved" },
      { name: "NOC", status: "Approved" },
    ],
    documentsData: {
      propertyType: "Bungalow",
      channel: [{ ownerNum: 1, ownerName: "Rahul Singh" }],
      loanAmount: 0,
      isFlat: "No",
      propertyData: {
        complaincesFollowed: "Yes",
        parkingAlloted: "Yes",
        towerNumber: null,
        flatNumber: null,
        size: null,
        noOfRooms: 7,
        bathroomAttached: "Yes",
        kitchenProvided: "Yes",
        isFurnished: "Yes",
      },
      isNoObjection: "Yes",
      societyMaintenanceAmountPending: 0,
    },
  },
];

export default dataSet;
